### ISSUE TITLE
panic send to closed channel on example auth

### ISSUE THREAD

**Issue by r1se** [aopoltorzhicky/go_kraken#24]
Hi.
Issue with send on closed channel.
[Example](https://github.com/aopoltorzhicky/go_kraken/blob/master/examples/auth/main.go)

```

goroutine 72 [running]:
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).close(0xc001112500, 0x0, 0x0)
        /home/dvp/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.11-0.20201213152921-5fae33b60384/client.go:285 +0xc8
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).exit(0xc001112500, 0x0, 0x0, 0x0, 0x0)
        /home/dvp/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.11-0.20201213152921-5fae33b60384/client.go:258 +0x52
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).reconnect(0xc001112500, 0x0, 0x0, 0x0, 0x0)
        /home/dvp/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.11-0.20201213152921-5fae33b60384/client.go:222 +0x7a
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).listenDisconnect(0xc001112500)
        /home/dvp/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.11-0.20201213152921-5fae33b60384/client.go:149 +0x357
created by github.com/aopoltorzhicky/go_kraken/websocket.(*Client).reset
        /home/dvp/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.11-0.20201213152921-5fae33b60384/client.go:189 +0x67
panic: send on closed channel

goroutine 30 [running]:
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).close(0xc001112500, 0xdc0ca0, 0xc00018e230)
        /home/dvp/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.11-0.20201213152921-5fae33b60384/client.go:283 +0xad
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).exit(0xc001112500, 0xdc0ca0, 0xc00018e230, 0x0, 0x0)
        /home/dvp/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.11-0.20201213152921-5fae33b60384/client.go:258 +0x52
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).reconnect(0xc001112500, 0xdc0ca0, 0xc00018e230, 0x0, 0x0)
        /home/dvp/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.11-0.20201213152921-5fae33b60384/client.go:245 +0x5d0
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).listenDisconnect(0xc001112500)
        /home/dvp/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.11-0.20201213152921-5fae33b60384/client.go:149 +0x357
created by github.com/aopoltorzhicky/go_kraken/websocket.(*Client).reset
        /home/dvp/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.11-0.20201213152921-5fae33b60384/client.go:189 +0x67

```

**Comment by aopoltorzhicky** [comment]
Thank you for the issue! I fixed it in new [release](https://github.com/aopoltorzhicky/go_kraken/releases/tag/websocket%2Fv0.1.0). But interface of library was fully changed! Be careful during update package!
